name: NodeJS with Grunt

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - run: echo "---Start checkout"
    
    - uses: actions/checkout@v4

    - run: echo "---Finish checkout"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: echo "---Finish node setup"

    - name: Build
      run: |
        npm install
        grunt

    - run: echo "---Finish build"

    - name: Deploy
      uses: fuddster/scoutingPASS-config-tool@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
            
